[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
bsc_testnet = "https://data-seed-prebsc-1-s1.binance.org:8545"
goat_testnet3 = "https://rpc.testnet3.goat.network"
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"

[etherscan]
bsc_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/api" }
goat_testnet3 = { key = "${GOAT_SCAN_API_KEY}", url = "https://explorer.testnet3.goat.network/api" }
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
